cmake_minimum_required(VERSION 2.6)
	add_executable(constructor constructor.cpp
	               arithmetic arithmetic.cpp
		       abstract abstractCpp.cpp
		       advance advance.cpp
		       auto auto.cpp
		       break break.cpp
	               digitsep digit_sep.cpp
                       beginend begin_end.cpp
                       bool bool.cpp
		       callByRef call_by_ref.cpp
		       case case.cpp
		       classCpp classCpp.cpp
		       continue continue.cpp
		       constoverload constoverload.cpp
		       destructor destructor.cpp
		       enum enum.cpp
		       extern extern.cpp
		       forloop forloop.cpp
		       friend friend.cpp
		       funsover funsover.cpp
		       funstemp funstemp.cpp
		       goto goto.cpp)
		       
